In [1]:
import numpy as np

In [2]:
#Can use any numpy function by just calling it eg
the_array=np.array([1,2,3,4,5])
print("The array should appear here: ", the_array)
print("Type: ", type(the_array))

The array should appear here:  [1 2 3 4 5]
Type:  <class 'numpy.ndarray'>


In [3]:
#multi_dimensional array
array=np.array([["Cate", "Jude", "Brian"], [1,2,3]])
array

array([['Cate', 'Jude', 'Brian'],
       ['1', '2', '3']], dtype='<U11')

In [2]:
import numpy as np
import time

#Using 1million integers
huge_list_of_integers=list(range(0, 1000000))
huge_np_array_of_integers=np.array(huge_list_of_integers)


def add_one(list_of_ints):
    return [num + 1 for num in list_of_ints]

start_time = time.perf_counter() # Time when operation starts
add_one(huge_list_of_integers) # Adds 1 to each number in the list of integers above
end_time = time.perf_counter() # Time when operation finishes
total_time = (end_time - start_time) # Total time for operation

start_time_with_np = time.perf_counter() # Time when operation starts
huge_np_array_of_integers + 1 # Adds 1 to each number in the array of integers
end_time_with_np = time.perf_counter() # Time when operation finishes
total_time_with_np = (end_time_with_np - start_time_with_np) # Total time for operation

print('Time it takes to add 1 to each element in a list without NumPy:', total_time)
print('Time it takes to add 1 to each element in a list with NumPy:', total_time_with_np)

percent_faster = int((((total_time - total_time_with_np)/total_time)*100))
print('NumPy completes the operation', percent_faster, '% faster than a traditional list')

Time it takes to add 1 to each element in a list without NumPy: 0.09248780000052648
Time it takes to add 1 to each element in a list with NumPy: 0.06172040000001289
NumPy completes the operation 33 % faster than a traditional list


In [3]:
np_array=np.array([1,2,3])
print(type(np_array))

<class 'numpy.ndarray'>


Broadcasting mathematical operations

In [4]:
np_array * 2

array([2, 4, 6])

In [5]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
np_array + 2

array([3, 4, 5])

In [7]:
# An ordinary nested list
y = [[1, 2], [3, 4]]
print(type(y))
y

<class 'list'>


[[1, 2], [3, 4]]

In [8]:
# Reformatted as a NumPy array
y = np.array([[1, 2], [3, 4]])
print(type(y))
y

<class 'numpy.ndarray'>


array([[1, 2],
       [3, 4]])

In [10]:
y.shape #prints rows and columns

(2, 2)

In [11]:
y = np.array([[1, 2],[3, 4],[5, 6]])
print(y.shape)
y

(3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
y = np.array([[[1, 2],[3, 4],[5, 6]],
             [[1, 2],[3, 4],[5, 6]]
             ])
print(y.shape)
y

(2, 3, 2)


array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

In [13]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(x.shape)
x

(4, 3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
# Retrieving the first row
x[0]

array([1, 2, 3])

In [15]:
# Retrieving all rows after the first row
x[1:]

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# All rows, column 0
x[:,0]