<a href="https://colab.research.google.com/github/JemmyKuria/Data_Science/blob/main/NumpyLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing numpy
import numpy as np

In [3]:
#Using a range 2. Using a Python list Below, create a list in Python that has 5 elements (i.e. [0,1,2,3,4]) and assign it to the variable py_list.
py_list=list(range(5))
py_list

[0, 1, 2, 3, 4]

In [9]:
py_range = range(0, 5)
py_range

range(0, 5)

In [10]:
#Create numpy arrays and Assign py_list to array_from_list and the same to py_range
array_from_list=np.array(py_list)
array_from_range= np.array(py_range)

In [11]:
# Use the conversion rate for turning height in inches to meters
list_height_inches = [65, 68, 73, 75, 78]

# Your code here
array_height_inches = np.array(list_height_inches)
conversion_rate = 0.0254
array_height_meters = array_height_inches * conversion_rate
array_height_meters

array([1.651 , 1.7272, 1.8542, 1.905 , 1.9812])

In [13]:
# Use the conversion rate for turning weight in pounds to kilograms
list_weight_pounds = [150, 140, 220, 205, 265]

# Your code here
array_weight_pounds = np.array(list_weight_pounds)
conversion=2.2046
array_weight_kg = array_weight_pounds / conversion
array_weight_kg

array([ 68.03955366,  63.50358342,  99.79134537,  92.98739   ,
       120.20321147])

In [14]:
#Calculating BMI
BMI_array=array_weight_kg/array_height_meters**2
BMI_array

array([24.9613063 , 21.28692715, 29.02550097, 25.62324316, 30.62382485])

In [15]:
#Create a vector of ones the same size as your BMI vector using np.ones()
identity=np.ones(len(BMI_array))
identity

array([1., 1., 1., 1., 1.])

In [16]:
#Multiply the BMI_array by your vector of ones
BMI_array*identity

array([24.9613063 , 21.28692715, 29.02550097, 25.62324316, 30.62382485])

In [18]:
# Open a text file (csv files are just plaintext separated by commas)
f = open('bp.txt')
n_rows = len(f.readlines())
# Print number of lines in the file
print('The file has {} lines.'.format(n_rows))
# After using readlines, we must reopen the file
f = open('bp.txt')
# The file has values separated by tabs; we read the first line and check it's length
n_cols = (len(f.readline().split('\t')))

f = open('bp.txt')
#1) Create a matrix of zeros that is the same size of the file
matrix = np.zeros([n_rows, n_cols])
#2) Iterate through the file: "for line in f:"
for n, line in enumerate(f):
    #3) Update each row of the matrix with the new stream of data
    #Hint: skip the first row (it's just column names, not the data.)
    if n > 0:
        matrix[n,:] = line.split('\t')
#4) Preview your results; you should now have a NumPy matrix with the data from the file
matrix


The file has 21 lines.


array([[  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
       [  1.  , 105.  ,  47.  ,  85.4 ,   1.75,   5.1 ,  63.  ,  33.  ],
       [  2.  , 115.  ,  49.  ,  94.2 ,   2.1 ,   3.8 ,  70.  ,  14.  ],
       [  3.  , 116.  ,  49.  ,  95.3 ,   1.98,   8.2 ,  72.  ,  10.  ],
       [  4.  , 117.  ,  50.  ,  94.7 ,   2.01,   5.8 ,  73.  ,  99.  ],
       [  5.  , 112.  ,  51.  ,  89.4 ,   1.89,   7.  ,  72.  ,  95.  ],
       [  6.  , 121.  ,  48.  ,  99.5 ,   2.25,   9.3 ,  71.  ,  10.  ],
       [  7.  , 121.  ,  49.  ,  99.8 ,   2.25,   2.5 ,  69.  ,  42.  ],
       [  8.  , 110.  ,  47.  ,  90.9 ,   1.9 ,   6.2 ,  66.  ,   8.  ],
       [  9.  , 110.  ,  49.  ,  89.2 ,   1.83,   7.1 ,  69.  ,  62.  ],
       [ 10.  , 114.  ,  48.  ,  92.7 ,   2.07,   5.6 ,  64.  ,  35.  ],
       [ 11.  , 114.  ,  47.  ,  94.4 ,   2.07,   5.3 ,  74.  ,  90.  ],
       [ 12.  , 115.  ,  49.  ,  94.1 ,   1.98,   5.6 ,  71.  ,  21.  ],
       [ 13.  , 114.  ,  50.  ,  91.6 ,   2.05,  10